name: CI/CD Pipeline for my_app

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t <image_name>:<tag> .
          docker tag <image_name>:<tag> <registry>/<image_name>:<tag>
          docker push <registry>/<image_name>:<tag>

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: <host_address>
          username: <user>
          key: <ssh_private_key>
          script: |
            cd <app_directory>
            docker pull <registry>/<image_name>:<tag>
            docker compose down
            docker compose up -d
